# Site settings
title:          Beyond The Notebook
description:    "Augusto Castro"
url:            "https://augustocast.github.io"

# i18n
default_lang:   es

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Augusto Castro
  url:          https://augustocast.github.io
  email:        castroaugusto3@gmail.com
  twitter:      augustocastr0
  linkedin:     augustocast
  picture:      /assets/foto_cv.jpg
  github:       augustocast

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Defaults
defaults:
  - scope:
      path: ""
    values:
      lang: es
  - scope:
      path: "_posts/en"
    values:
      lang: en
  - scope:
      path: "_pages/en"
    values:
      lang: en

# Disqus (Set to your disqus id)
disqus:         jekyll-tale